INSERT INTO posts (title, author, genre, rating, date, excerpt, review, cover_image, tags, is_favorite, instagram_url) VALUES
('Les Furtifs', 'Alain Damasio', 'Science-Fiction', 5, '2025-01-15', 'Un chef-d''oeuvre de la SF francaise qui repousse les limites du langage et de l''imagination.', 'Alain Damasio nous offre avec Les Furtifs une oeuvre monumentale. Dans un futur ou les villes sont privatisees, Lorca part a la recherche de sa fille disparue, devenue peut-etre l''une de ces creatures insaisissables : les furtifs. La prose de Damasio est une experience sensorielle unique, melant neologismes, jeux typographiques et une musicalite envoutante. Ce roman est autant une critique sociale acerbe qu''une ode a la liberte et a l''invisible.', '/placeholder.svg?height=400&width=300', ARRAY['sf-francaise', 'damasio', 'dystopie', 'langage', 'coup-de-coeur'], true, NULL),

('La Passe-miroir, tome 1', 'Christelle Dabos', 'Fantasy', 4.5, '2025-01-28', 'Ophélie nous embarque dans un univers fascinant de Arches flottantes et de mystères politiques.', 'Christelle Dabos cree avec La Passe-miroir un univers d''une richesse remarquable. Ophélie, jeune femme capable de lire le passé des objets et de traverser les miroirs, est envoyée au Pôle pour un mariage arrangé avec Thorn. L''écriture est élégante, le world-building méticuleux, et les personnages d''une profondeur rare. On tourne les pages avec avidité.', '/placeholder.svg?height=400&width=300', ARRAY['fantasy-francaise', 'dabos', 'passe-miroir', 'magie'], true, NULL),

('Le Comte de Monte-Cristo', 'Alexandre Dumas', 'Classique', 5, '2025-02-05', 'Le roman de la vengeance ultime. Dumas au sommet de son art narratif.', 'Que dire de ce monument de la littérature qui n''ait déjà été dit ? Dumas tisse une intrigue d''une complexité vertigineuse autour d''Edmond Dantès, trahi et emprisonné, qui revient sous l''identité du Comte pour orchestrer sa vengeance. C''est un roman sur la patience, la justice et le prix de la rancune. Chaque page est un délice.', '/placeholder.svg?height=400&width=300', ARRAY['classique', 'dumas', 'vengeance', 'aventure', 'chef-doeuvre'], true, NULL),

('Nuit du faune', 'Romain Lucazeau', 'Science-Fiction', 4, '2025-02-12', 'Une rencontre entre le dernier être humain et une entité cosmique, entre poésie et hard SF.', 'Romain Lucazeau signe un court roman d''une beauté saisissante. À la fin des temps, une faune — dernière représentante de l''humanité — rencontre une intelligence cosmique. Leur dialogue est une méditation sur la conscience, le sens de l''existence et la place de l''éphémère dans l''infini. La prose est ciselée, parfois exigeante, mais toujours récompensante.', '/placeholder.svg?height=400&width=300', ARRAY['sf', 'lucazeau', 'philosophie', 'cosmique'], false, NULL),

('L''Anomalie', 'Hervé Le Tellier', 'Contemporain', 3.5, '2025-02-20', 'Prix Goncourt 2020, un roman puzzle qui joue avec les genres et les identités.', 'Hervé Le Tellier construit un roman kaléidoscopique où un vol Paris-New York se dédouble littéralement. Les passagers doivent affronter leur propre copie. C''est drôle, vertigineux, et parfois un peu froid dans son intellectualisme. Un exercice de style brillant qui questionne l''identité, mais qui peut laisser certains lecteurs sur leur faim émotionnellement.', '/placeholder.svg?height=400&width=300', ARRAY['contemporain', 'goncourt', 'le-tellier', 'identite'], false, NULL),

('Berserk', 'Kentaro Miura', 'BD & Manga', 5, '2025-03-01', 'L''oeuvre d''une vie. Berserk transcende le manga pour atteindre l''universel.', 'Que vous soyez lecteur de manga ou non, Berserk est une oeuvre qui mérite votre attention. Kentaro Miura a passé sa vie à sculpter cette fresque dark fantasy d''une intensité émotionnelle et graphique sans égale. Guts, le guerrier noir, traverse un monde cruel avec une détermination qui force l''admiration. Le dessin est d''une minutie hallucinante. Un monument.', '/placeholder.svg?height=400&width=300', ARRAY['manga', 'miura', 'dark-fantasy', 'seinen', 'chef-doeuvre'], true, NULL),

('Les Fleurs du Mal', 'Charles Baudelaire', 'Poésie', 5, '2025-03-10', 'La beauté dans la laideur, le sublime dans le spleen. Baudelaire éternel.', 'Relire Les Fleurs du Mal, c''est redécouvrir à chaque vers pourquoi Baudelaire a révolutionné la poésie. Entre spleen et idéal, entre fascination morbide et quête de beauté absolue, chaque poème est un joyau ciselé. « L''invitation au voyage », « Correspondances », « Une charogne » — autant de textes qui continuent de résonner avec une modernité troublante.', '/placeholder.svg?height=400&width=300', ARRAY['poesie', 'baudelaire', 'classique', 'spleen', 'fleurs-du-mal'], true, NULL),

('La Horde du Contrevent', 'Alain Damasio', 'Science-Fiction', 4.5, '2025-03-18', 'Vingt-trois caractères face au vent. Une odyssée littéraire unique en son genre.', 'Avant Les Furtifs, Damasio avait déjà marqué la SF avec cette oeuvre chorale. La Horde, composée de 23 membres, remonte un vent cosmique pour trouver son origine. Chaque personnage a sa propre typographie, sa propre voix. C''est exigeant, tourbillonnant, et absolument magnifique. Un roman qui se vit autant qu''il se lit.', '/placeholder.svg?height=400&width=300', ARRAY['sf-francaise', 'damasio', 'vent', 'chorale', 'aventure'], false, NULL),

('Métro 2033', 'Dmitry Glukhovsky', 'Thriller', 4, '2025-03-25', 'Dans les entrailles du métro de Moscou, l''humanité survit après l''apocalypse.', 'Glukhovsky transforme le métro de Moscou en un monde souterrain fascinant et terrifiant. Artyom doit traverser les stations, chacune devenue une micro-civilisation avec ses propres règles. L''atmosphère est oppressante, les dangers omniprésents. C''est un thriller post-apocalyptique qui pose aussi des questions philosophiques profondes sur la nature humaine.', '/placeholder.svg?height=400&width=300', ARRAY['thriller', 'post-apo', 'glukhovsky', 'russie', 'metro'], false, NULL),

('Soie', 'Alessandro Baricco', 'Roman', 4.5, '2025-04-02', 'Un conte délicat sur l''amour et l''absence, d''une brièveté lumineuse.', 'En à peine 100 pages, Baricco tisse une histoire d''une délicatesse infinie. Hervé Joncour, négociant en vers à soie, voyage au Japon et croise le regard d''une femme. C''est un roman sur le désir inassouvi, la distance et les fils invisibles qui nous relient. La prose est musicale, chaque phrase pèse son poids de silence. Un bijou.', '/placeholder.svg?height=400&width=300', ARRAY['roman', 'baricco', 'japon', 'amour', 'poesie-en-prose'], true, NULL),

('Le Petit Prince', 'Antoine de Saint-Exupéry', 'Classique', 5, '2025-04-10', 'On ne voit bien qu''avec le coeur. L''essentiel est invisible pour les yeux.', 'Chaque relecture du Petit Prince révèle de nouvelles couches de sens. Ce qui semble être un conte pour enfants est en réalité une méditation profonde sur l''amour, l''amitié, la perte et le sens de la vie. Saint-Exupéry parle aux enfants que nous avons été et aux adultes que nous sommes devenus. Indémodable et bouleversant.', '/placeholder.svg?height=400&width=300', ARRAY['classique', 'saint-exupery', 'conte', 'philosophie', 'intemporel'], false, NULL),

('L''Assassin royal, tome 1', 'Robin Hobb', 'Fantasy', 4, '2025-04-18', 'Fitz, bâtard royal et assassin, dans une fantasy intimiste et politique.', 'Robin Hobb prend le contrepied de la fantasy épique avec ce premier tome introspectif. Fitz grandit à la cour, apprend les arts de l''assassinat et découvre le Vif, un pouvoir mal vu. C''est lent, contemplatif, et profondément humain. Hobb excelle dans la psychologie de ses personnages. Un premier tome qui pose les bases d''une saga monumentale.', '/placeholder.svg?height=400&width=300', ARRAY['fantasy', 'hobb', 'assassin-royal', 'introspectif', 'politique'], false, NULL),

('Blast', 'Manu Larcenet', 'BD & Manga', 4.5, '2025-04-25', 'Une BD coup de poing sur la marginalité, la violence et la quête de transcendance.', 'Polza Mancini est un homme massif, en marge de la société, interrogé par la police. Au fil de ses aveux, on découvre son histoire, sa quête du « Blast » — un moment de transcendance absolue. Larcenet livre un récit d''une puissance graphique et émotionnelle rare. Le noir et blanc est saisissant. Ce n''est pas une lecture facile, mais c''est une lecture nécessaire.', '/placeholder.svg?height=400&width=300', ARRAY['bd', 'larcenet', 'noir-et-blanc', 'marginalite', 'transcendance'], true, NULL),

('La Nuit des temps', 'René Barjavel', 'Science-Fiction', 4, '2025-05-03', 'Une histoire d''amour traversant les millénaires, entre SF et romantisme.', 'Barjavel mêle avec brio science-fiction et romance dans ce classique. Une expédition en Antarctique découvre des êtres humains en hibernation depuis 900 000 ans. Éléa et Païkan portent une histoire d''amour qui transcende le temps, tandis que le monde moderne s''entre-déchire pour leur technologie. C''est daté sur certains aspects mais l''émotion reste intacte.', '/placeholder.svg?height=400&width=300', ARRAY['sf', 'barjavel', 'classique-sf', 'amour', 'antarctique'], false, NULL),

('Nous sommes l''incendie', 'Vincent Villeminot', 'Jeunesse', 4, '2025-05-10', 'Un roman jeunesse ambitieux sur la révolte, l''écologie et le prix de l''engagement.', 'Villeminot n''écrit pas « pour les jeunes » : il écrit avec eux. Ce roman choral suit des adolescents engagés dans la lutte écologique, confrontés à la violence du système et à leurs propres contradictions. C''est brûlant, engagé, et d''une honnêteté rare. Un texte qui ne sous-estime jamais son lectorat et qui résonne avec l''urgence de notre époque.', '/placeholder.svg?height=400&width=300', ARRAY['jeunesse', 'ya', 'ecologie', 'revolte', 'villeminot'], false, NULL),

('Vernon Subutex', 'Virginie Despentes', 'Contemporain', 4, '2025-05-18', 'Fresque sociale foisonnante, Vernon Subutex ausculte la France contemporaine.', 'Vernon, ancien disquaire, se retrouve à la rue. Autour de lui gravite une galaxie de personnages qui forment un portrait kaléidoscopique de la société française. Despentes écrit avec une rage froide et une lucidité implacable. C''est cru, politique, et addictif. La trilogie complète est un tour de force.', '/placeholder.svg?height=400&width=300', ARRAY['contemporain', 'despentes', 'social', 'paris', 'trilogie'], false, NULL);
